# "Παράγουμε" το k08.a απλά αντιγράφοντας το αρχείο που αντιστοιχεί στο λειτουργικό σύστημα που χρησιμοποιούμε
DiseaseMonitorLibToUse.a:
	cp DiseaseMonitorLib.a DiseaseMonitorLibToUse.a

clean:
	$(RM) DiseaseMonitorLibToUse.a